image: mcr.microsoft.com/dotnet/sdk:6.0-alpine

stages:
- build
- pack
- deploy

variables:
  CONFIGURATION: Release
  GIT_STRATEGY: clone

build:
  stage: build
  script:
  - dotnet build

  cache: &cache_template
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - ./src/*/bin/*
    policy: push

pack:
  stage: pack
  script:
  - dotnet pack --output "$(pwd)/dist/"
  cache:
    <<: *cache_template
    policy: pull
  artifacts:
    paths:
    - ./dist/

deploy:
  stage: deploy
  script:
  - dotnet nuget push --api-key "${NUGET_API_KEY}" ./dist/*.nupkg
  only:
    refs:
    - main
