image: mcr.microsoft.com/dotnet/core/sdk:3.1-alpine

stages:
- build
- pack
- deploy

variables:
  CONFIGURATION: Release

build:
  stage: build
  script:
  - dotnet build
  cache: &cache_template
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - ./src/*/bin/*
    policy: push

pack:
  stage: pack
  script:
  - dotnet pack --output ./dist/
  cache:
    <<: *cache_template
    policy: pull
  artifacts:
    paths:
    - ./dist/

deploy:
  stage: deploy
  script:
  - dotnet nuget push ./dist/*.nupkg --api-key "${NUGET_API_KEY}"
  only:
    refs:
    - main
