image: microsoft/dotnet:2.1-sdk-alpine

stages:
  - build
  - pack
  - deploy

cache:
  key: "$CI_PIPELINE_ID"

build:
  stage: build
  script:
    - dotnet build -c Release
  artifacts:
    untracked: true

pack:
  stage: pack
  script:
    - dotnet pack -c Release -o "$(pwd)/dist/"
  artifacts:
    untracked: false
    paths:
      - dist/

deploy:
  stage: deploy
  script:
    - dotnet nuget push ./dist/*.nupkg -k $NUGET_API_KEY
  only:
    - master
